### ISSUE TITLE
We need a functional description of our data

### ISSUE THREAD

**Issue by thewickedaxe** [Upward-Spiral-Science/spect-team#1]
More specifically we need a description of what each feature in the set of feature vectors for spect data mean,

For example
1. What do columns like BSC? GSC, LDS and doa mean?
2. Why are certain fields blank? or have NA values? how are they supposed to be interpreted?

**Comment by jovo** [comment]
1) i'm not sure.  swing by my office 2pm on tues and we'll figure it out?
2) also not sure, i recommend trying to figure out how to remove subjects/columns with NA/missing values.
