### ISSUE TITLE
Shed some light on feature selection

### ISSUE THREAD

**Issue by thewickedaxe** [Upward-Spiral-Science/spect-team#3]
We are unable to draw conclusions from trying to corroborate the literature with the SPECT data. Can you suggest some ways in which we can employ more rigorous feature selection techniques and maybe look at other options?

**Comment by jovo** [comment]
here is my favorite approach: http://www.ncbi.nlm.nih.gov/pubmed/25640961

do you have any other ideas?

On Tue, Apr 12, 2016 at 5:23 PM, Srinivas Suresh Kumar <
notifications@github.com> wrote:

> We are unable to draw conclusions from trying to corroborate the
> literature with the SPECT data. Can you suggest some ways in which we can
> employ more rigorous feature selection techniques and maybe look at other
> options?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/spect-team/issues/3

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by thewickedaxe** [comment]
thank you Jovo,

I will look into that
I was looking at feature selection modules [here](http://scikit-learn.org/stable/modules/feature_selection.html#recursive-feature-elimination) which are implemented as part of scikit learn. i do not fully understand what they are about, but do you feel they are worth exploring?

**Comment by jovo** [comment]
yah, the 2 common things are forward selection and backward elimination.
wikipedia explains them reasonably well.
you still need to specify what is the criteria for adding/removing another
feature.

actually, citation 2 & 3 from the article i sent where the approaches that
i really like.  but the default python ones are certainly easier and worth
trying first.

if you can't figure them out, let me know, and i can explain.

On Tue, Apr 12, 2016 at 8:57 PM, Srinivas Suresh Kumar <
notifications@github.com> wrote:

> thank you Jovo,
> 
> I will look into that
> I was looking at feature selection modules here
> http://scikit-learn.org/stable/modules/feature_selection.html#recursive-feature-elimination
> which are implemented as part of scikit learn. i do not fully understand
> what they are about, but do you feel they are worth exploring?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/spect-team/issues/3#issuecomment-209170066

## 

the glass is all full:  half water, half air.
neurodata.io
